### ISSUE TITLE
validator set is empty after InitGenesis

### ISSUE THREAD

**Issue by 0xx92** [settlus/chain#195]
I deployed the node according to the documentation, but the node is not working properly, here is the error message：

[genesis.json](https://github.com/user-attachments/files/16507859/genesis.json)
**panic: validator set is empty after InitGenesis, please ensure at least one validator is initialized with a delegation greater than or equal to the DefaultPowerReduction ({824638998816})**

**Comment by jacobhjkim** [comment]
which document are your referring to? you can generate working `genesis.json` with the [ignite CLI](https://docs.ignite.com/)
```shell
$ ignite chain init --skip-proto
```

**Comment by 0xx92** [comment]
I would like to confirm if the chainid of the testnet node we are currently running is settlus_5372-1 or settlus_5372-2 or settlus_5371-1
<img width="735" alt="settlus" src="https://github.com/user-attachments/assets/208bc299-7e16-4026-9b01-ac679b2162a5">
<img width="675" alt="settlus2" src="https://github.com/user-attachments/assets/a3d50e03-1960-4f79-b5d0-0fa582308f87">
<img width="710" alt="settlus3" src="https://github.com/user-attachments/assets/4ea0aafe-754f-4ff9-ba36-f441c3179e1f">

**Comment by 0xx92** [comment]
The chainid in the genesis file generated after the command you gave me to initialise is settlus_5371_1，The chainid in the official documentation is another two

**Comment by jacobhjkim** [comment]
- mainnet chain ID: `settlus_5371-{VERSION}`
- testnet chain ID: `settlus_5372-{VERSION}`

since we updated our testnet to version 2, current testnet chain ID is `settlus_5372-2`.  you can change the chain ID in [`config.yml`](https://github.com/settlus/chain/blob/ac331b3b25e821fd1f79ac7b1738c11b96c1fd48/config.yml#L101). the chain in your `genesis.json` is derived from the `config.yml` above.

However, it's important to note that we are PoSA chain and we are **not accepting** new validators as of right now.

**Comment by 0xx92** [comment]
thanksthanks
